@startuml
skinparam shadowing false
hide stereotype
hide empty members
skinparam nodesep 50
skinparam ranksep 40
skinparam ArrowThickness 0.6
skinparam defaultFontSize 12
skinparam FolderBorderColor #333333
skinparam FolderBackgroundColor #ffffff
skinparam folder<<dynamic>> BackgroundColor #fff7e6
skinparam folder<<dynamic>> BorderColor #d46b08
skinparam folder<<static>> BackgroundColor #f0f5ff
skinparam folder<<static>> BorderColor #1d39c4

folder "AssistantActions" as AssistantActions <<dynamic>> #e8e8ffff
folder "Conditions" as Conditions #ffedcaff
folder "EventRegistration" as EventRegistration <<dynamic>> #f1f1f1ff
folder "KeySituations" as KeySituations <<dynamic>> #e8faffff
folder "Metrics" as Metrics <<dynamic>> #ffe8e8ff
folder "MotivationalMechanics" as MotivationalMechanics <<static>> #f5ffdbff
folder "Usertrait_Mechanic_Mapping" as Usertrait_Mechanic_Mapping <<static>> #f5ffdbff
folder "PlanAndTasks" as PlanAndTasks <<static>> #ebffe8ff
folder "UserProfile" as UserProfile #fde8ffff
folder "UserTraits" as UserTraits <<static>> #fafeb7ff

' relations (with cardinalities when present)
AssistantActions --> "0..1" MotivationalMechanics : toggles
Usertrait_Mechanic_Mapping --> MotivationalMechanics : maps
Usertrait_Mechanic_Mapping --> UserTraits : maps
MotivationalMechanics "1" --> "1..2" UserProfile : selected_by
AssistantActions "1" --> "1" MotivationalMechanics : toggles
AssistantActions "1" --> "1..*" UserProfile : targets
EventRegistration "1..*" --> "0..*" KeySituations : triggers
UserProfile --> "1..*" UserTraits : references
EventRegistration "1..*" --> "0..*" Metrics : triggers recalculation
Metrics "1" --> "1" EventRegistration : calculated from
KeySituations "1" --> "0..*" AssistantActions : triggers
UserProfile "1" --> "1..*" UserTraits : references
UserProfile "1" --> "1..*" AssistantActions : receives
UserProfile --> Metrics : "is defined by"
UserProfile "1" --> "1" PlanAndTasks : has
EventRegistration "1" --> "1" PlanAndTasks : refers
MotivationalMechanics "1" --> "1" Metrics : is_determined_by
MotivationalMechanics "1" --> "1" Metrics : reads
AssistantActions "1" --> "1..*" Conditions : has
KeySituations "1" --> "1..*" Conditions : has
Conditions "1" --> "1..*" Metrics : reads
Conditions "1" --> "1..*" MotivationalMechanics : reads
Conditions "1" --> "1..*" PlanAndTasks : reads
Conditions "1" --> "1..*" UserProfile : considers
Conditions "1" --> "1" UserProfile : considers
MotivationalMechanics "1" --> "1..*" Metrics : based on
@enduml
