skinparam linetype polyline
hide empty methods
hide empty attributes
hide empty members
left to right direction
skinparam nodesep 40
skinparam ranksep 40
skinparam packageStyle rectangle

!define actionsBack #e8e8ffff
!define actionsFront #cacaffff
!define actionsLight #d6d6ffff

package AssistantActions actionsBack {
  class AssistantAction actionsFront {
    +timestamp: DateTime
  }

  class UserCommunication actionsLight extends AssistantAction
  class MotivationalMessage actionsLight extends UserCommunication
  class RewardNotification actionsLight extends UserCommunication
  class AchievementNotification actionsLight extends UserCommunication
  class UnlockNotification actionsLight extends UserCommunication

  class MechanicStateUpdate actionsLight extends UserCommunication

  class SocialNotification actionsLight extends UserCommunication
  class SocialComparisonNotification actionsLight extends SocialNotification
  class SocialEncouragementNotification actionsLight extends SocialNotification
  class SocialInvitationNotification actionsLight extends SocialNotification
  class SocialSharingNotification actionsLight extends SocialNotification

  class Questionnaire actionsLight extends AssistantAction
  class IntrinsicMotivationInventory actionsLight extends Questionnaire
  class UserEngagementScale actionsLight extends Questionnaire
  class SystemNotice actionsLight extends UserCommunication
  class PromptMessage actionsLight extends UserCommunication

  class SystemAction actionsLight extends AssistantAction

  !if ($renderMode != "master")
  AssistantActions.SystemAction --> "0..1" MotivationalMechanics.MotivationalMechanic : toggles
  !endif
}
