@startuml
skinparam linetype polyline
hide empty methods
hide empty attributes
hide empty members
left to right direction
skinparam nodesep 40
skinparam ranksep 40
skinparam packageStyle rectangle

!define conditionsBack #ffedcaff
!define conditionsFront #f8db92ff

package Conditions conditionsBack {
  class Condition conditionsFront {
    +timestamp: DateTime
    +value: float
  }
  class UserBehaviourCondition conditionsFront extends Condition
  class AdherenceLow conditionsFront extends UserBehaviourCondition
  class ConfidenceLow conditionsFront extends UserBehaviourCondition

  class SystemCondition conditionsFront extends Condition
  class TimeOfDayCondition conditionsFront extends SystemCondition

  class PlanCondition conditionsFront extends Condition
  class HalfwayPointReached conditionsFront extends PlanCondition
}

@enduml
