skinparam linetype polyline
!if ($renderMode != "master")
!pragma layout smetana
!endif
hide empty methods
hide empty attributes
hide empty members
left to right direction
skinparam nodesep 40
skinparam ranksep 40
skinparam packageStyle rectangle

!define conditionsBack #ffedcaff
!define conditionsFront #f8db92ff

package Conditions conditionsBack {
  class Condition conditionsFront {
    +timestamp: DateTime
    +value: float
  }
  class UserStateCondition conditionsFront extends Condition
  class AdherenceLow conditionsFront extends UserStateCondition
  class ConfidenceLow conditionsFront extends UserStateCondition

  class SystemCondition conditionsFront extends Condition
  class TimeOfDayCondition conditionsFront extends SystemCondition

  class PlanCondition conditionsFront extends Condition
  class HalfwayPointReached conditionsFront extends PlanCondition

  !if ($renderMode != "master")
  package Metrics #ffe8e8ff {
    class Metric #fda5a5ff
  }
  package MotivationalMechanics #f5ffdbff {
    class MechanicState #e4ffa0ff
  }
  package PlanAndTasks #ebffe8ff {
    class Plan #lightgreen
  }
  Condition --> "1..*" Metrics.Metric : considers
  Condition --> "1..*" MotivationalMechanics.MechanicState : considers
  PlanCondition --> "1..*" PlanAndTasks.Plan : "is related to"
  !endif
}

