@startuml
skinparam linetype polyline
hide empty methods
hide empty attributes
hide empty members
left to right direction
skinparam nodesep 40
skinparam ranksep 40
skinparam packageStyle rectangle

!define eventsBack #f1f1f1ff
!define eventsFront #ccccccff
!define eventsLight #e6e6e6ff

package EventRegistration eventsBack {

  class Event eventsFront {
    + timestamp: DateTime
  }

  together {
    class UserEvent eventsLight extends Event
    class SystemEvent eventsLight extends Event
    class TaskEvent eventsLight extends UserEvent
    class MechanicEvent eventsLight extends UserEvent
  }

  together {
    class ClickEvent eventsLight extends UserEvent
    class LoginEvent eventsLight extends UserEvent
    class LogoutEvent eventsLight extends UserEvent
    class ErrorCommittedEvent eventsLight extends UserEvent
    class ScoreEvent eventsLight extends UserEvent
    class ScreenVisitedEvent eventsLight extends UserEvent

    class HourPassedEvent eventsLight extends SystemEvent
    class DayPassedEvent eventsLight extends SystemEvent
    class WeekPassedEvent eventsLight extends SystemEvent

    class TaskStartedEvent eventsLight extends TaskEvent
    class TaskFinishedEvent eventsLight extends TaskEvent

    class MechanicDisplayedEvent eventsLight extends MechanicEvent
    class MechanicInteractedEvent eventsLight extends MechanicEvent
    class MechanicDismissedEvent eventsLight extends MechanicEvent
  }

}
@enduml