skinparam linetype polyline
hide empty methods
hide empty attributes
hide empty members
left to right direction
skinparam nodesep 40
skinparam ranksep 40
skinparam packageStyle rectangle

!define keySituationsBack #e8faffff
!define keySituationsFront #bbf0ffff
!define keySituationsLight #d5f6ffff

package KeySituations keySituationsBack {
  class KeySituation keySituationsFront
  class MechanicDisplayedKeySituation keySituationsLight extends KeySituation
  class MechanicInteractionKeySituation keySituationsLight extends KeySituation
  class MilestoneReachedKeySituation keySituationsLight extends KeySituation
  class DailyChallengePosedKeySituation keySituationsLight extends KeySituation
  class SessionStartedKeySituation keySituationsLight extends KeySituation
  class TaskStartedKeySituation keySituationsLight extends KeySituation
  class TaskFinishedKeySituation keySituationsLight extends KeySituation
  class SessionEndedKeySituation keySituationsLight extends KeySituation
  note left of KeySituation
  Generic KeySituation structure for behavioral logs.
  end note
}
