@startuml

skinparam linetype polyline
hide empty methods
hide empty attributes
hide empty members
left to right direction
skinparam nodesep 40
skinparam ranksep 40
skinparam packageStyle rectangle
title Motiva Framework Ontology

!$renderMode= "master"
skinparam class {
  StereotypeFontStyle bold
}

!include ./user_traits.puml
!include ./motivational_mechanics.puml
!include ./metrics.puml
!include ./keysituations.puml
!include ./assistantActions.puml
!include ./event_registration.puml
!include ./plan_and_tasks.puml
!include ./user_context.puml
!include ./conditions.puml
!include ./relationships.puml


@enduml
