@startuml

skinparam linetype polyline
hide empty methods
hide empty attributes
hide empty members
top to bottom direction
skinparam nodesep 100
skinparam ranksep 130
skinparam packageStyle rectangle
title Motiva Framework Ontology

!$renderMode = "master"
skinparam class {
  StereotypeFontStyle bold
}

!include ./user_traits.puml
!include ./motivational_mechanics.puml
!include ./metrics.puml
!include ./keysituations.puml
!include ./assistantActions.puml
!include ./event_registration.puml
!include ./PlanAndTasks.puml
!include ./user.puml
!include ./conditions.puml
!include ./relationships.puml


@enduml
