@startuml
skinparam linetype polyline
hide empty methods
hide empty attributes
hide empty members
left to right direction
skinparam nodesep 40
skinparam ranksep 40
skinparam packageStyle rectangle

!define metricsBack #ffe8e8ff
!define metricsFront #fda5a5ff
!define metricsLight #ffcdcdff

package Metrics metricsBack {
  class Metric metricsFront {
    +timestamp: DateTime
    +value: float
  }
  class AdherenceMetric metricsLight extends Metric
  class EngagementMetric metricsLight extends Metric
  class PerformanceMetric metricsLight extends Metric
  class SystemMetric metricsLight extends Metric

  class DailyAdherence metricsLight extends AdherenceMetric
  class WeeklyAdherence metricsLight extends AdherenceMetric
  class MechanicUsageRate metricsLight extends EngagementMetric
  class MechanicDisplayRate metricsLight extends EngagementMetric
  class MechanicEngagement metricsLight extends EngagementMetric
  class SessionDuration metricsLight extends SystemMetric
  class ClickRate metricsLight extends PerformanceMetric
  class Adherence metricsLight extends AdherenceMetric
  class HesitationTime metricsLight extends PerformanceMetric

}

@enduml
