skinparam linetype polyline
skinparam packageStyle rectangle
left to right direction

hide empty methods
hide empty attributes
hide empty members

!define mechanicsBack        #f5ffdbff
!define mechanicsFront      #e4ffa0ff

scale 0.8
skinparam nodesep 16
skinparam ranksep 18
skinparam PackageTitleFontSize 11
skinparam ClassFontSize 11
skinparam ClassAttributeFontSize 10
skinparam ClassStereotypeFontSize 10
skinparam NoteFontSize 10

package MotivationalMechanics mechanicsBack {
  left to right direction

  class MotivationalMechanic mechanicsFront
  hide MotivationalMechanic members

  class MechanicState mechanicsFront

  class ProgressIndicator mechanicsFront extends MotivationalMechanic

  class CompetitionWithOthers mechanicsFront extends MotivationalMechanic
  hide CompetitionWithOthers members

  class PersonalGoals mechanicsFront extends MotivationalMechanic
  hide PersonalGoals members

  class PersonalizationAndCreativity mechanicsFront extends MotivationalMechanic
  hide PersonalizationAndCreativity members

  class SharingAchievements mechanicsFront extends MotivationalMechanic
  hide SharingAchievements members

  class SocialNetworking mechanicsFront extends MotivationalMechanic
  hide SocialNetworking members

  class SurprisesAndEvents mechanicsFront extends MotivationalMechanic
  hide SurprisesAndEvents members

  class MotivationalMessages mechanicsFront extends MotivationalMechanic
  hide MotivationalMessages members

  class TimeBasedChallenges mechanicsFront extends MotivationalMechanic
  hide TimeBasedChallenges members

  class RewardsAndUnlocks mechanicsFront extends MotivationalMechanic
  hide RewardsAndUnlocks members

  class MechanicUserTraitMapping mechanicsFront {
    +weight: float
  }

  MechanicUserTraitMapping --> MotivationalMechanics.MotivationalMechanic : maps

  !if ($renderMode != "master")
  package UserTraits #fafeb7ff {
    class UserTrait #f5fba0ff
  }
  MechanicUserTraitMapping --> UserTraits.UserTrait : maps
  !endif

  MotivationalMechanic "1" --> "1" MechanicState : has
}
