@startuml
Metrics -[hidden]-> EventRegistration
EventRegistration -[hidden]-> KeySituations
KeySituations -[hidden]-> AssistantActions
AssistantActions -[hidden]-> UserContext
UserContext -[hidden]-> UserTraits
UserTraits -[hidden]-> MotivationalMechanics

MotivationalMechanics.MotivationalMechanic "1" --> "1..2" UserContext.UserTraitWeight : selected_by

'AssistantActions.AssistantAction --> "0..1" MotivationalMechanics.MotivationalMechanic : toggles
AssistantActions.AssistantAction --> "0..*" UserContext.User : targets

EventRegistration.Event "1..*" --> "0..*" KeySituations.KeySituation : triggers

EventRegistration.Event "1..*" --> "0..*" Metrics.Metric : triggers recalculation
Metrics.Metric "1" --> "1" EventRegistration.Event   : calculated from

KeySituations.KeySituation "1" --> "0..*" AssistantActions.AssistantAction : triggers

UserContext.UserTraitWeight "1" --> "1..*" UserTraits.UserTrait : references
UserContext.User "1" --> "1..*" AssistantActions.AssistantAction : receives
UserContext.User --> Metrics.Metric : has

UserContext.User "1" --> "1" Plan_and_Tasks.Plan : has

EventRegistration.TaskEvent "1" --> "1" Plan_and_Tasks.Task : refers

MotivationalMechanics.MotivationalMechanic "1" --> "1" Metrics.Metric : is_determined_by

MotivationalMechanics.Usertrait_Mechanic_Mapping.Level_and_Experience_Point_System_to_Player --> UserTraits.Player : maps
MotivationalMechanics.Usertrait_Mechanic_Mapping.Level_and_Experience_Point_System_to_Player --> MotivationalMechanics.Level_and_Experience_Point_System : maps

User --> UserEvent : executes

MotivationalMechanics.MotivationalMechanic "1" --> "1" Metrics.Metric : reads

AssistantActions.AssistantAction "1" --> "1..*" Conditions.Condition : has

Conditions.Condition "1" --> "1..*" Metrics.Metric : reads
Conditions.PlanCondition "1" --> "1..*" Plan_and_Tasks.Plan : reads

Conditions.Condition "1" --> "1..*" UserContext.UserTraitWeight : considers
Conditions.Condition "1" --> "1" UserContext.UserState : considers

MotivationalMechanics.MechanicState --> Metrics.Metric : based on
@enduml
