
MotivationalMechanics.MotivationalMechanic "1" --> "1..2" UserProfile.UserTraitMapping : "determined by"

AssistantActions.SystemAction "1" --> "0..1" MotivationalMechanics.MotivationalMechanic : toggles
AssistantActions.AssistantAction "1" --> "1..*" UserProfile.User : targets

EventRegistration.Event "1..*" --> "0..*" KeySituations.KeySituation : triggers

UserProfile.UserTraitMapping --> "1..*" UserTraits.UserTrait : references
MotivationalMechanics.MechanicUserTraitMapping --> UserTraits.UserTrait : maps

EventRegistration.Event "1..*" --> "0..*" Metrics.Metric : "triggers recalculation"

KeySituations.KeySituation "1" --> "0..*" AssistantActions.AssistantAction : triggers

UserProfile.User "1" --> "1..*" AssistantActions.AssistantAction : receives
UserProfile.User --> Metrics.Metric : "is defined by"

UserProfile.User "1" --> "1" PlanAndTasks.Plan : has

EventRegistration.TaskEvent "1" --> "1" PlanAndTasks.Task : "refers to"
PlanAndTasks.Task --> PlanAndTasks.Level : "has available"

UserProfile.User --> EventRegistration.UserEvent : executes

AssistantActions.AssistantAction "1" --> "1..*" Conditions.Condition : has

KeySituations.KeySituation "1" --> "1..*" Conditions.Condition : has

Conditions.Condition "1" --> "1..*" Metrics.Metric : considers
Conditions.Condition "1" --> "1..*" MotivationalMechanics.MechanicState : considers
Conditions.PlanCondition "1" --> "1..*" PlanAndTasks.Plan : "is related to"

Conditions.Condition "1" --> "1..*" UserProfile.UserTraitMapping : considers
Conditions.Condition "1" --> "1" UserProfile.UserState : considers

UserProfile.UserState --> "1..*" Metrics.UserStateMetric : "is defined by"

MotivationalMechanics.MechanicState "1" --> "1..*" Metrics.Metric : based on
