skinparam linetype polyline
hide empty methods
hide empty attributes
hide empty members
left to right direction
skinparam nodesep 40
skinparam ranksep 40
skinparam packageStyle rectangle

!define traitsBack        #fafeb7ff
!define traitsFront      #f5fba0ff

package UserTraits traitsBack {
  class UserTrait traitsFront

  class MotivationalTrait traitsFront extends UserTrait
  hide MotivationalTrait members

  class PlayerType traitsFront extends UserTrait

  class DigitalLiteracy traitsFront extends UserTrait
  hide DigitalLiteracy members

  class CognitiveAbility traitsFront extends UserTrait
  hide CognitiveAbility members

  class AttentionSpan traitsFront extends UserTrait
  hide AttentionSpan members

  class SelfDiscipline traitsFront extends UserTrait
  hide SelfDiscipline members

  class FrustrationTolerance traitsFront extends UserTrait
  hide FrustrationTolerance members
}
