@startuml
skinparam linetype polyline
hide empty methods
hide empty attributes
hide empty members
left to right direction
skinparam nodesep 40
skinparam ranksep 40
skinparam packageStyle rectangle

!define contextBack #fde8ffff
!define contextFront #f59bffff
!define contextState #f7befeff
!define contextLight #f5c6fbff

package UserContext contextBack {
  class User contextFront

  class UserState contextState {
    +timestamp: DateTime
  }

  class MotivationalState contextState extends UserState
  class Low contextLight extends MotivationalState
  class Medium contextLight extends MotivationalState
  class High contextLight extends MotivationalState

  class CognitiveLoadState contextState extends UserState
  class Underchallenged contextLight extends CognitiveLoadState
  class OptimalLoad contextLight extends CognitiveLoadState
  class Overloaded contextLight extends CognitiveLoadState

  class UserTraitMapping contextState {
    +weight: float
  }

  User --> "1..*" UserState : has
  User --> "1..*" UserTraitMapping : has
}
@enduml
